vich_uploader:
  db_driver: orm

  mappings:
    book_image:
      uri_prefix: /images/book
      upload_destination: '%kernel.project_dir%/public/images/book'
      namer: Vich\UploaderBundle\Naming\OrignameNamer
