version: '3'

services:
  app:
    build:
      context: ./docker/php-fpm
      dockerfile: Dockerfile
    container_name: app_it_library
    volumes:
      - .:/var/www
    ports:
      - "9000:9000"
  nginx:
    image: nginx:latest
    container_name: nginx_it_library
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www
    depends_on:
      - app
  mysql:
    image: mysql:5.7
    container_name: db_it_library
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: it-library
      MYSQL_USER: admin
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:

